source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
plugin "cocoapods-acknowledgements"
target 'GdanskBus' do
  pod 'Alamofire', '~> 3.4'
  pod 'RealmSwift'
  pod 'AlamofireObjectMapper', '~> 3.0'
  pod 'MBProgressHUD', '~> 0.9.2'
  pod 'GoogleMaps'
  pod 'CPDAcknowledgements'  
end
